# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bfb4adeb2a5bac7c4f9c03785e872d3a65738ec8155e3434462e10411eb770ef449ba475a075fb601c5827f2a4cfef22e5157d1d983e35d1b8a8458c680780b

test:
  secret_key_base: add82dbedee1af752f2ebf4b427762fd4fe4bd12e068a4f7eced68e3f1235475d6908912555f3109a29f9e50344ce021dfaac601ee7bc4af2abeef9800b47526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
